lib/lv_chat_web/router.ex
defmodule LvChatWeb.Router do
  use LvChatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug LvChatWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # scope "/", LvChatWeb do
  #   pipe_through :browser

  #   get "/", PageController, :index
  #   resources "/users", UserController, only: [:new, :create]
  #   resources "/sessions", SessionController, only: [:new, :create, :delete]
  # end
  scope "/", LvChatWeb do
    pipe_through :browser

    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create]
  end

  scope "/", LvChatWeb do
    pipe_through [:browser, :authenticate_user]

    get "/", PageController, :index
    resources "/sessions", SessionController, only: [:delete]
    resources "/boards", BoardController # add this
  end


  # Other scopes may use custom stacks.
  # scope "/api", LvChatWeb do
  #   pipe_through :api
  # end
end

lib/lv_chat_web/views/layout_view.ex
defmodule LvChatWeb.LayoutView do
  use LvChatWeb, :view
end

lib/lv_chat_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>LvChat · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <%= if @current_user do %>
              <li><%= @current_user.name %></li>
              <li>
                <%= link "Logout",
                      to: Routes.session_path(@conn, :delete, @current_user),
                      method: "delete" %>
              </li>
            <% else %>
              <li><%= link "Sign Up", to: Routes.user_path(@conn, :new) %></li>
              <li><%= link "Sign In", to: Routes.session_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>