lib/lv_chat_web/router.ex
defmodule LvChatWeb.Router do
  use LvChatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug LvChatWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # scope "/", LvChatWeb do
  #   pipe_through :browser

  #   get "/", PageController, :index
  #   resources "/users", UserController, only: [:new, :create]
  #   resources "/sessions", SessionController, only: [:new, :create, :delete]
  # end
  scope "/", LvChatWeb do
    pipe_through :browser

    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create]
  end

  scope "/", LvChatWeb do
    pipe_through [:browser, :authenticate_user]

    get "/", PageController, :index
    resources "/sessions", SessionController, only: [:delete]
    resources "/boards", BoardController # add this
  end


  # Other scopes may use custom stacks.
  # scope "/api", LvChatWeb do
  #   pipe_through :api
  # end
end

lib/lv_chat_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "LiveView Chat" %></h1>
  <%= link "掲示板へ", to: Routes.board_path(@conn, :index) %>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>